
            FROM node:carbon
            WORKDIR /usr/src/VisualizarEventosPresentation.App
            COPY . .
            CMD [ "node", "server/VisualizarEventosPresentation.App.js" ]
            