
            FROM node:carbon
            WORKDIR /usr/src/reproduzircalculotaxapresentation.app
            COPY . .
            CMD [ "node", "server/reproduzircalculotaxapresentation.app.js" ]
            