
            FROM node:carbon
            WORKDIR /usr/src/ConsultarMemoriaCalculoPresentation.App
            COPY . .
            CMD [ "node", "server/ConsultarMemoriaCalculoPresentation.App.js" ]
            